Don't crash QuickContacts because of null uri
When composeQuickContactActivity() is passed a null uri, then
startActivity throws the following exception:

    ActivityNotFoundException: No Activity found to handle Intent
    { act=android.provider.action.QUICK_CONTACT flg=0x20000000 (has extras) }

I can't reproduce this. So lets just fix the crash.

Inside contact list fragments, ignore clicks on views bound to null uris.
We don't need to change Dialer. It already handles these cases.

Note that we can't fix this by checking for null URIs inside
ContactEntryListFragment. One of the Dialer subclasses of
ContactEntryListFragment requires null URIs.

Bug: 17807956
Change-Id: I41dd878b23b8cc3e9b8ad49e12675a4da9ced466