Fix tests
- Fix testMigratePhoneFromGoogleToExchange

We forgot to update this test when we changed the default phone type
to MOBILE.

Bug 5928504

- Fix NoSuchMethodError

Now that Preconditions.* aren't used in the main source, these are stripped
down by proguard.  Don't use them in the test.

Change-Id: Idfeed7e92e4f95c150bcbc797e71b4e5fe9ef68b